# Generated by Django 3.2.13 on 2022-06-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Вакансии',
            },
        ),
    ]
