# Generated by Django 3.2.13 on 2022-06-17 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_licensecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='license',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.licensecategory', verbose_name='Категория'),
        ),
    ]
